// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//  import 'firebase_options.dart';
//  // ...
//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDip5xEZ3ai9ac9TC87p6QqfdPWZIAT3_c',
    appId: '1:10615049727:web:ae2ab2bb2f1a9fbf3a6bca',
    messagingSenderId: '10615049727',
    projectId: 'my-first-firebase-e4fc9',
    authDomain: 'my-first-firebase-e4fc9.firebaseapp.com',
    storageBucket: 'my-first-firebase-e4fc9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0a8dkHYQaNmw2xgjdiRaFG_L5z9i5on4',
    appId: '1:10615049727:android:d01e1872f174399e3a6bca',
    messagingSenderId: '10615049727',
    projectId: 'my-first-firebase-e4fc9',
    storageBucket: 'my-first-firebase-e4fc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz7hAXcQ0YJnRiYVL3kXUCNFhYHxc0pbc',
    appId: '1:10615049727:ios:7bfea1e1c7403c543a6bca',
    messagingSenderId: '10615049727',
    projectId: 'my-first-firebase-e4fc9',
    storageBucket: 'my-first-firebase-e4fc9.appspot.com',
    iosBundleId: 'com.example.flutterapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz7hAXcQ0YJnRiYVL3kXUCNFhYHxc0pbc',
    appId: '1:10615049727:ios:10a7602441cfe6d63a6bca',
    messagingSenderId: '10615049727',
    projectId: 'my-first-firebase-e4fc9',
    storageBucket: 'my-first-firebase-e4fc9.appspot.com',
    iosBundleId: 'com.example.flutterapp2.RunnerTests',
  );
}
